### ISSUE TITLE
Suggestions of improvement in code 

### ISSUE THREAD

**Issue by dqarias** [ElsonOtake/Portfolio#6]
Hi Elson 👋 ,

Good job so far! 🎉 🎉 🎉 
There are some suggestions that you can change to improve your code.

- [x]  Kindly delete the commented code, which keeps your code clean.
- [x]  You can add multiple bacgroud images to one element

> #example1 {
  background-image: url(img_flwr.gif), url(paper.gif);
  background-position: right bottom, left top;
  background-repeat: no-repeat, repeat;
}

- [x]  It is not a good practice to use fixed height and width for HTML elements for it makes your page not responsive try to delete.

**Comment by ElsonOtake** [comment]
Every day I learn new things and I'd like to thank you for the valuable tips. I used it all in the project.
